// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlOIC-z7IraEJc-q9Tn6CmhoeEmyZhrI4',
    appId: '1:1078951071571:web:99b924a0e896342b165ba6',
    messagingSenderId: '1078951071571',
    projectId: 'fir-tutorial-c1497',
    authDomain: 'fir-tutorial-c1497.firebaseapp.com',
    storageBucket: 'fir-tutorial-c1497.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdPAX7kbuz4OfeS7Jv6STn-LzKp9c5t-w',
    appId: '1:1078951071571:android:63a0fd9762d7d920165ba6',
    messagingSenderId: '1078951071571',
    projectId: 'fir-tutorial-c1497',
    storageBucket: 'fir-tutorial-c1497.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD9aAH-G2ABy3cLkDUlndMANmSkUJr8M0',
    appId: '1:1078951071571:ios:a973ab7bdd1fcc25165ba6',
    messagingSenderId: '1078951071571',
    projectId: 'fir-tutorial-c1497',
    storageBucket: 'fir-tutorial-c1497.firebasestorage.app',
    iosBundleId: 'com.example.demoProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD9aAH-G2ABy3cLkDUlndMANmSkUJr8M0',
    appId: '1:1078951071571:ios:a973ab7bdd1fcc25165ba6',
    messagingSenderId: '1078951071571',
    projectId: 'fir-tutorial-c1497',
    storageBucket: 'fir-tutorial-c1497.firebasestorage.app',
    iosBundleId: 'com.example.demoProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlOIC-z7IraEJc-q9Tn6CmhoeEmyZhrI4',
    appId: '1:1078951071571:web:4e984438236c0b78165ba6',
    messagingSenderId: '1078951071571',
    projectId: 'fir-tutorial-c1497',
    authDomain: 'fir-tutorial-c1497.firebaseapp.com',
    storageBucket: 'fir-tutorial-c1497.firebasestorage.app',
  );
}
